
version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
     
      - checkout
      - node/install:
          install-yarn: true
          node-version: '14.15.1'
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run api:build
      - run :
          name: s3 bucket deploy
          command: |
            npm run deploy:frontend
      - run :
          name: api deploy
          command: |
            npm run deploy:backend
workflows:
  build:   
    jobs:
      - build:  
          filters:
            branches:
              only:
                - master
  
